version: "3.8"

services:
  nestjs-app:
    container_name: nestjs_container
    build: .
    restart: always
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: ["npm", "run", "start:prod"]
