version: "3.8"

services:
  nestjs-app:
    container_name: nestjs_container
    build: .
    restart: always
    ports:
      - "3000:3000"  # Bu yönlendirme 3003 portunu dışarıya açar, 3000 portu konteyner içinde çalışıyor
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: ["npm", "run", "start:prod"]
 